config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  devise_for :users, skip: :all
    as :user do
      get "/login" => "users/sessions#new", :as => :new_user_session
      post "/login" => "users/sessions#create", :as => :user_session
      delete "/logout" => "users/sessions#destroy", :as => :destroy_user_session
      get "/register" => "users/registrations#new", :as => :new_user_registration
      post "/register" => "users/registrations#create", :as => :user_registration
    end

  namespace :users do
      resources :profiles, only: [:show, :edit, :update]
      resources :order_histories
  end

  namespace :manager do
    root "dashboard#index"
    resources :category
    resources :products
    resources :notifications
    resources :orders
    mount ActionCable.server => '/cable'
    resources :users
  end

  devise_for :admins, controllers: {
    sessions: "manager/admins/sessions",
  }, path: "admin", path_names: { sign_in: "login" }

  resource :quick_views
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :reviews
  resources :product_orders, only: [:create, :destroy]
  resources :orders
  resources :notifications
  resources :checkouts
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :admin, optional: true
  belongs_to :order, optional: true
  belongs_to :user, optional: true

  scope :unread,->{where opened_at: nil}
  scope :check, -> (user_id){ where opened_at: nil, user_id: user_id }

  def perform
    ActionCable.server.broadcast "notifications_channel",
    notification: ApplicationController.renderer.render(partial: "manager/notifications/notification", locals: { notification: self }), counter: ApplicationController.renderer.render(partial: "manager/notifications/counter", locals: { counter: Notification.unread.size })
  end

  def perform_1
    ActionCable.server.broadcast "notifications_channel_#{self.user_id}",
      notification: ApplicationController.renderer.render(partial: "notifications/notification", locals: { notification: self }), counter: ApplicationController.renderer.render(partial: "notifications/counter", locals: { counter: Notification.check(self.user_id).size })
  end
end

app/views/notifications/_counter.html.erb
<i class="fa fa-bell-o fa-2x"></i>
<span id="notification-counter" class="count-style"><%= counter %></span>

app/views/notifications/_notification.html.erb
<li>
  Order Code <b><strong>
    <%= link_to "#{notification.order_id}", users_order_history_path(notification.order_id, notification: notification.id) %></strong> was <%= notification.event %></b><br>
  <span><small>At <%= notification.created_at.strftime("%d %b. %Y") %></small></span>
</li>

app/views/notifications/_notification_center.html.erb
<ul class="notificator">
  <a href="#" id="notification" style="position: relative;">
    <%= render 'notifications/counter', counter: Notification.check(current_user.id).size %>
  </a>
  <div id="notificationContainer">
    <div id="notificationsBody" class="notifications">
      <div id="notificationTitle">Notifications</div>
      <ul id="notificationListUser" style="margin-top: 60px; padding: 5px;">
        <%= render partial: "notifications/notification", collection: notifications, as: :notification  %>
      </ul>
    </div>
  </div>
</ul>