config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  devise_for :users, skip: :all
    as :user do
      get "/login" => "users/sessions#new", :as => :new_user_session
      post "/login" => "users/sessions#create", :as => :user_session
      delete "/logout" => "users/sessions#destroy", :as => :destroy_user_session
      get "/register" => "users/registrations#new", :as => :new_user_registration
      post "/register" => "users/registrations#create", :as => :user_registration
    end

  namespace :users do
      resources :profiles, only: [:show, :edit, :update]
      resources :order_histories
  end

  namespace :manager do
    root "dashboard#index"
    resources :category
    resources :products
    resources :notifications
    resources :orders
    mount ActionCable.server => '/cable'
    resources :users
  end

  devise_for :admins, controllers: {
    sessions: "manager/admins/sessions",
  }, path: "admin", path_names: { sign_in: "login" }

  resource :quick_views
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :reviews
  resources :product_orders, only: [:create, :destroy]
  resources :orders
  resources :notifications
  resources :checkouts
end

app/views/layouts/admin/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <nav>
      <ul class="footer-menu">
        <li>
          <a href="#">
            Home
          </a>
        </li>
        <li>
          <a href="#">
            Company
          </a>
        </li>
        <li>
          <a href="#">
            Portfolio
          </a>
        </li>
        <li>
          <a href="#">
            Blog
          </a>
        </li>
      </ul>
      <p class="copyright text-center">
        ©
        <script>
          document.write(new Date().getFullYear())
        </script>
        <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
      </p>
    </nav>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
  <div class="container-fluid">
    <a class="navbar-brand" href="#pablo"> Dashboard </a>
    <button href="" class="navbar-toggler navbar-toggler-right" type="button"
    data-toggle="collapse" aria-controls="navigation-index"
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-bar burger-lines"></span>
      <span class="navbar-toggler-bar burger-lines"></span>
      <span class="navbar-toggler-bar burger-lines"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <ul class="nav navbar-nav mr-auto">
        <li class="nav-item">
          <a href="#" class="nav-link" data-toggle="dropdown">
            <i class="nc-icon nc-palette"></i>
            <span class="d-lg-none">Dashboard</span>
          </a>
        </li>
        <li class="dropdown nav-item">
          <%= render "manager/notifications/notification_center", notifications: notifications %>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nc-icon nc-zoom-split"></i>
            <span class="d-lg-block">&nbsp;Search</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="#pablo">
            <span class="no-icon">Account</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href=""
          id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false" style="margin-right: 30px">
            <span class="no-icon"><%= current_admin.email.split("@")[0] %></span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Something </a>
            <div class="divider"></div>
            <%= link_to "Logout", destroy_admin_session_path, method: :delete,
              :class => "dropdown-item", :style => "color:red" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<div class="sidebar" data-image="../assets/admin/sidebar-4.jpg" data-color="purple">
  <div class="sidebar-wrapper">
    <div class="logo">
      <%= link_to manager_root_path, class: "simple-text" do  %>
        Shop Project
      <% end %>
    </div>
    <ul class="nav">
      <li class="nav-item active">
        <%= link_to manager_root_path, class: "nav-link" do %>
          <i class="nc-icon nc-chart-pie-35"></i>
          <p>Dashboard</p>
        <% end %>
      </li>
      <li>
        <%= link_to manager_users_path, class: "nav-link" do %>
          <i class="nc-icon nc-tag-content"></i>
          <p>User List</p>
        <% end %>
      </li>
      <li>
        <%= link_to manager_products_path, class: "nav-link" do %>
          <i class="nc-icon nc-notes"></i>
          <p>Product</p>
        <% end %>
      </li>
      <li>
          <%= link_to manager_orders_path, class: "nav-link" do %>
            <i class="nc-icon nc-bullet-list-67"></i>
            <p>Order List</p>
          <% end %>
        </a>
      </li>
      <li>
        <%= link_to manager_category_index_path, class: "nav-link" do %>
          <i class="nc-icon nc-tag-content"></i>
          <p>Category</p>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopProject</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= stylesheet_link_tag "admin/application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag "admin/application", "data-turbolinks-track": "reload" %>
</head>
<body>
  <div class="wrapper">
    <%= render "layouts/admin/sidebar" %>
    <div class="main-panel">
      <%= render "layouts/admin/header", notifications: @notifications %>
      <script type="text/javascript">
        <% flash.each do |f| %>
         <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
      </script>
      <%= yield %>
      <%= render "layouts/admin/footer" %>
    </div>
  </div>
</body>
</html>