config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  devise_for :users, skip: :all
    as :user do
      get "/login" => "users/sessions#new", :as => :new_user_session
      post "/login" => "users/sessions#create", :as => :user_session
      delete "/logout" => "users/sessions#destroy", :as => :destroy_user_session
      get "/register" => "users/registrations#new", :as => :new_user_registration
      post "/register" => "users/registrations#create", :as => :user_registration
    end

  namespace :users do
      resources :profiles, only: [:show, :edit, :update]
      resources :order_histories
  end

  namespace :manager do
    root "dashboard#index"
    resources :category
    resources :products
    resources :notifications
    resources :orders
    mount ActionCable.server => '/cable'
    resources :users
  end

  devise_for :admins, controllers: {
    sessions: "manager/admins/sessions",
  }, path: "admin", path_names: { sign_in: "login" }

  resource :quick_views
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :reviews
  resources :product_orders, only: [:create, :destroy]
  resources :orders
  resources :notifications
  resources :checkouts
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :profile, dependent: :destroy
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :notifications, dependent: :destroy

  scope :group_by_type, -> (type) {
     case type
     when "day"
       group("DATE_FORMAT(created_at, '%d-%b-%x')").count
     when "week"
       group("DATE_FORMAT(created_at,'Week %v')").count
     when "month"
       group("DATE_FORMAT(created_at,'%b-%x')").count
     end
   }

  class << self
    def all_data_user
      data = []
      day = group_by_type("day")
      date = day.keys
      user = day.values
      max = 14
      title = "Daily"
      data << {"date" => date, "user" => user, "max" => max, "title" => title}
    end
    def all_data_user1
      data = []
      week = group_by_type("week")
      date = week.keys
      user = week.values
      max = week.size-1
      title = "Weekly"
      data << {"date" => date, "user" => user, "max" => max, "title" => title}
    end
    def all_data_user2
      data = []
      month = group_by_type("month")
      date = month.keys
      user = month.values
      max = month.size-1
      title = "Monthly"
      data << {"date" => date, "user" => user, "max" => max, "title" => title}
    end
  end

  def lock_user
    update locked_at: Time.zone.now
  end

  def unlock_user
    update locked_at: nil
  end

end

app/controllers/manager/admins/sessions_controller.rb
# frozen_string_literal: true
module Manager
  module Admins
    class SessionsController < Devise::SessionsController
      layout "login/application"
      # before_action :configure_sign_in_params, only: [:create]

      # GET /resource/sign_in
      # def new
      #   super
      # end

      # POST /resource/sign_in
      # def create
      #   super
      # end

      # DELETE /resource/sign_out
      # def destroy
      #   super
      # end

      # protected

      # If you have extra params to permit, append them to the sanitizer.
      # def configure_sign_in_params
      #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
      # end
    end
  end
end

app/controllers/manager/base_controller.rb
class Manager::BaseController < ActionController::Base
  before_action :authenticate_admin!
  layout "admin/application"
  before_action :set_notification

  def set_notification
    @notifications = Notification.unread.limit(10)
  end
end

app/controllers/manager/category_controller.rb
class Manager::CategoryController < Manager::BaseController

  def index
    @categories = Category.order("created_at desc")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      @categories = Category.order("created_at desc")
    else
      render :"new_invalid"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes category_params
      @categories = Category.order("created_at desc")
    else
      render :"edit_invalid"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    @categories = Category.order("created_at desc")
  end

  private

  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < Manager::BaseController
  def index
    if params[:type] == "month"
      @data_user = User.all_data_user2
      @data_order = Order.all_data_order2
      @data_product = Product.all_data_product2
    elsif params[:type] == "week"
      @data_user = User.all_data_user1
      @data_order = Order.all_data_order1
      @data_product = Product.all_data_product1
    else
      @data_user = User.all_data_user
      @data_order = Order.all_data_order
      @data_product = Product.all_data_product
    end
  end
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < Manager::BaseController
  before_action :load_order, except: [:index, :new, :create]

  def index
    @orders = Order.order("created_at desc")
    if params[:notification]
      @notification = Notification.find params[:notification]
      @notification.update opened_at: Time.zone.now
    end
  end

  def show
    @order = Order.find params[:id]
    respond_to do |format|
      format.js
    end
  end

  def edit; end

  def update
    @order.update status: params[:status]
    @orders = Order.order("created_at desc")
    @notification = Notification.create(user_id: @order.user_id, event: @order.status, order_id: @order.id)
    @notification.perform_1
  end

  def destroy
    @order.destroy
    @orders = Order.order("created_at desc")
    respond_to do |format|
      format.js
    end
  end

  private

  def load_order
    @order = Order.find params[:id]
  end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < Manager::BaseController
  before_action :load_product, only: [:edit, :update, :destroy]
  before_action :product_categories

  def index
    @products = Product.order("created_at DESC")
  end

  def new
    @product = Product.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @product = Product.new product_params
    if @product.save
      @products = Product.order("created_at DESC")
      respond_to do |format|
        format.js
      end
    else
      render "new_form"
    end
  end

  def edit; end

  def update
    @product.update product_params
    @products = Product.order("created_at DESC")
    respond_to do |format|
      format.js
    end

  end

  def destroy
    @product.destroy
    @products = Product.order("created_at DESC")
    respond_to do |format|
      format.js
    end
  end


  private

  def product_params
    params.require(:product).permit :name, :price, :image, :description, :category_ids, :sale_price
  end

  def load_product
    @product = Product.find params[:id]
  end

  def product_categories
    @product_categories = Category.pluck :name, :id
  end
end

app/controllers/manager/users_controller.rb
class Manager::UsersController < Manager::BaseController

  def index
    @users = User.order("created_at desc")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.create_profile
      @users = User.order("created_at desc")
      flash.now[:success] = "Add user success"
    else
      render "new_invalid"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:function] == "unlock"
      @user.unlock_user
      @users = User.order("created_at desc")
      flash.now[:success] = "Unlock user success"
    elsif params[:function] == "lock"
      @user.lock_user
      @users = User.order("created_at desc")
      flash.now[:success] = "Lock user success"
    elsif params[:function] == "update" && @user.update_attributes(user_params)
      @users = User.order("created_at desc")
      flash.now[:success] = "Update user success"
    else
      render "update_invalid"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @users = User.order("created_at desc")
    flash.now[:success] = "Delete user success" if @user.destroy
  end

  private

  def user_params
    if params[:user][:password].blank?
     params.require(:user).permit(:name, :email)
   else
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end
  end
end

app/controllers/users/order_histories_controller.rb
class Users::OrderHistoriesController < ApplicationController

  def index
    if user_signed_in?
      @orders = Order.where(user_id: current_user.id).page(params[:page]).per(5)
    else
      @orders = Order.where(id: session[:order_ids]).page(params[:page]).per(5)
    end
  end

  def show
    @order = Order.find_by(id: params[:id])
    if params[:notification]
      @order = Order.find_by(id: params[:id])
      @notification = Notification.find params[:notification]
      @notification.update opened_at: Time.zone.now
    end
  end

end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!
  def show
    @profile  = Profile.find_by(user_id: current_user.id)
  end

  def edit
    @profile  = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update_attributes(profile_params)
      sign_in @profile.user, :bypass => true
      flash[:success] = "Update profile success!"
      redirect_to users_profile_path
    else
      flash[:danger] = "Update faild"
      render :edit
    end
  end

  private

  def check_login
    unless user_signed_in?
      flash[:warning] = "You need login first"
      redirect_to new_user_session_url
    end
  end

  def profile_params
    if params[:profile][:user_attributes][:password].blank?
      params.require(:profile).permit(:avatar, :address, :phone, :facebook, :twitter, :instagram, user_attributes: [:id, :name])
    else
      params.require(:profile).permit(:avatar, :address, :phone, :facebook, :twitter, :instagram, user_attributes: [:id, :name,:password, :password_confirmation])
    end
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if resource.save
      resource.create_profile
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # #GET /resource/sign_in
  # def new
  #   super
  # end

  # #POST /resource/sign_in
  # def create
  #   super
  # end

  # #DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # #If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/manager/users/_form_add_user.html.erb
 <%= form_for user, url:  manager_users_path, remote: true do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
      <%= f.label :name, "Name:", class: "col-form-label" %>
      <%= f.text_field :name, class: "form-control", id: "recipient-name" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "Email:", class: "col-form-label" %>
      <%= f.text_field :email, class: "form-control", id: "recipient-name" %>
    </div>
    <div class="form-group">
      <%= f.label :password, "Password:", class: "col-form-label" %>
      <%= f.password_field :password, class: "form-control",
      id: "recipient-name" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Password confirmation:",
      class: "col-form-label" %>
      <%= f.password_field :password_confirmation, class: "form-control",
      id: "recipient-name" %>
    </div>
  <div class="modal-footer">
    <%= button_tag "Close", class: "btn btn-secondary",
    "data-dismiss": "modal" %>
    <%= f.submit "Submit", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/manager/users/_form_edit_user.html.erb
 <%= form_for user, url:  manager_user_path, remote: true do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
      <%= f.label :name, "Name:", class: "col-form-label" %>
      <%= f.text_field :name, class: "form-control", id: "recipient-name" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "Email:", class: "col-form-label" %>
      <%= f.text_field :email, class: "form-control", id: "recipient-name" %>
    </div>
    <div class="form-group">
      <%= f.label :password, "Password:", class: "col-form-label" %>
      <%= f.password_field :password, class: "form-control",
      id: "recipient-name" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Password confirmation:",
      class: "col-form-label" %>
      <%= f.password_field :password_confirmation, class: "form-control",
      id: "recipient-name" %>
    </div>
  <div class="modal-footer">
    <%= button_tag "Close", class: "btn btn-secondary",
    "data-dismiss": "modal" %>
    <%= f.submit "Submit", class: "btn btn-primary", name: "function",
    value: "update" %>
  </div>
<% end %>

app/views/manager/users/_modal_add_user.html.erb
<div class="modal fade" id="addUserFromAD" tabindex="-1" role="dialog"
aria-labelledby="addUserModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel"
        style="font-weight: bold;">New user</h3>
        <button type="button" class="close" data-dismiss="modal"
        aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "form_add_user", user: user %>
      </div>
    </div>
  </div>
</div>

app/views/manager/users/_modal_edit_user.html.erb
<div class="modal fade" id="editUserFromAD" tabindex="-1" role="dialog"
aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel"
        style="font-weight: bold;">Edit user</h3>
        <button type="button" class="close" data-dismiss="modal"
        aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "form_edit_user", user: user %>
      </div>
    </div>
  </div>
</div>

app/views/manager/users/_table.html.erb
<table id="category-table" class="table table-striped table-bordered"
style="width:100%">
  <thead>
    <tr>
      <th>ID_User</th>
      <th>Name</th>
      <th>Email</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th style="text-align: center !important;">Edit</th>
      <th style="text-align: center !important;">Delete</th>
      <th style="text-align: center !important;">Un/Lock</th>
    </tr>
    </tr>
  </thead>
  <% users.each do |u| %>
    <tr>
      <td><%= u.id %></td>
      <td><%= u.name %></td>
      <td><%= u.email %></td>
      <td><%= u.created_at.strftime("%d/%m/%Y") %></td>
      <td><%= u.updated_at.strftime("%d/%m/%Y") %></td>
      <td class="text-center">
        <%= link_to edit_manager_user_path(u), remote: true do %>
          <%= button_tag "Edit", class: "btn btn-primary",
          id: "btn-table-cate", style: "width: 45px" %>
        <% end %>
      </td>
      <td class="text-center">
        <%= link_to manager_user_path(u), method: :delete,
        data: {confirm: "You want delete user?"}, remote: true do %>
          <%= button_tag "Delete", class: "btn btn-primary", style: "width: 45px" %>
        <% end %>
      </td>
      <td style="text-align: center !important;">
        <%= link_to manager_user_path(u,
        function: u.locked_at? ? "unlock" : "lock"), method: :patch,
        data: {confirm: u.locked_at? ? "Confirm unlock user?" : "Confirm lock user?"},
        remote: true do %>
          <%= button_tag u.locked_at? ? "Unlock" : "Lock",
          class: "btn btn-danger", style: "width: 45px"%>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<script type="text/javascript">
  <% flash.each do |f| %>
  <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   toastr['<%= type %>']('<%= f[1] %>');
  <% end %>
</script>

app/views/manager/users/create.js.erb
$("#table-list-user").html("<%= j render "table", users: @users %>")
$('#addUserFromAD').modal('hide');
initDataTable();

app/views/manager/users/destroy.js.erb
$("#table-list-user").html("<%= j render "table", users: @users %>")
initDataTable();

app/views/manager/users/edit.js.erb
$("#editUser").html("<%= j render "modal_edit_user", user: @user %>");
$("#editUserFromAD").modal("show");

app/views/manager/users/index.html.erb
<div class="row">
  <div class="col-md-12" style="padding-right: 20px; padding-left: 20px">
    <%= link_to new_manager_user_path, remote: true do %>
      <%= button_tag "New user", class: "btn btn-primary",
      style: "margin: 10px 0" %>
    <% end %>
    <div id="table-list-user">
      <%= render "table", users: @users%>
    </div>
    <div id="addUser"></div>
    <div id="editUser"></div>
  </div>
</div>

app/views/manager/users/new.js.erb
$("#addUser").html("<%= j render "modal_add_user", user: @user %>");
$("#addUserFromAD").modal("show");

app/views/manager/users/new_invalid.js.erb
$(".modal-body").html("<%= j render "form_add_user", user: @user %>")

app/views/manager/users/update.js.erb
$("#table-list-user").html("<%= j render "table", users: @users %>")
$("#editUserFromAD").modal("hide");
initDataTable();

app/views/manager/users/update_invalid.js.erb
$(".modal-body").html("<%= j render "form_edit_user", user: @user %>")