config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  devise_for :users, skip: :all
    as :user do
      get "/login" => "users/sessions#new", :as => :new_user_session
      post "/login" => "users/sessions#create", :as => :user_session
      delete "/logout" => "users/sessions#destroy", :as => :destroy_user_session
      get "/register" => "users/registrations#new", :as => :new_user_registration
      post "/register" => "users/registrations#create", :as => :user_registration
    end

  namespace :users do
      resources :profiles, only: [:show, :edit, :update]
      resources :order_histories
  end

  namespace :manager do
    root "dashboard#index"
    resources :category
    resources :products
    resources :notifications
    resources :orders
    mount ActionCable.server => '/cable'
    resources :users
  end

  devise_for :admins, controllers: {
    sessions: "manager/admins/sessions",
  }, path: "admin", path_names: { sign_in: "login" }

  resource :quick_views
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :reviews
  resources :product_orders, only: [:create, :destroy]
  resources :orders
  resources :notifications
  resources :checkouts
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/category_controller.rb
class Admin::CategoryController < Admin::BaseController

  def index
    @categories = Category.order("created_at desc")
  end

  def new; end

  def create
    @category = Category.new category_params
    @category.save
    @categories = Category.order("created_at desc").page(params[:page]).per(10)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes category_params
    @categories = Category.order("updated_at desc").page(params[:page]).per(10)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    @categories = Category.order("updated_at desc").page(params[:page]).per(10)
  end

  private

  def category_params
    params.require(:category).permit :name
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find params[:id]
    @products = @category.products.page(params[:page]).per(20)
  end
end

app/controllers/manager/category_controller.rb
class Manager::CategoryController < Manager::BaseController

  def index
    @categories = Category.order("created_at desc")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      @categories = Category.order("created_at desc")
    else
      render :"new_invalid"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes category_params
      @categories = Category.order("created_at desc")
    else
      render :"edit_invalid"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    @categories = Category.order("created_at desc")
  end

  private

  def category_params
    params.require(:category).permit :name
  end
end

app/views/admin/category/_item.html.erb
<% categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.updated_at.strftime("%d/%m/%Y") %></td>
    <td><%= category.created_at.strftime("%d/%m/%Y") %></td>
    <td class="text-center">
      <%= link_to edit_admin_category_path(category), remote: true do %>
        <%= button_tag "Edit", class: "btn btn-primary", id: "btn-table-cate" %>
      <% end %>
    </td>
    <td class="text-center">
      <%= link_to admin_category_path(category), method: :delete, data: {confirm: "Delete?"}, remote: true do %>
        <%= button_tag "Delete", class: "btn btn-primary" %>
      <% end %>
      </td>
  </tr>
<% end %>
<div id="exampleModal02"></div>
<div id="exampleModal03"></div>

app/views/admin/category/_modal.html.erb
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create new category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for category, url: admin_category_path, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, "Name:", class: "col-form-label" %>
            <%= f.text_field :name, class: "form-control", id: "recipient-name" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag "Close", class: "btn btn-secondary", "data-dismiss": "modal" %>
          <%= f.submit "Update", class: "btn btn-primary", id: "editSubmit"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/category/_modal3.html.erb
<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create new category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for Category.new, url: admin_category_index_path, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, "Name:", class: "col-form-label" %>
            <%= f.text_field :name, class: "form-control", id: "recipient-name" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag "Close", class: "btn btn-secondary", "data-dismiss": "modal" %>
          <%= f.submit "Create", class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/category/index.html.erb
<div class="row">
  <div class="col-md-12" style="padding-right: 20px; padding-left: 20px">
    <%= link_to new_admin_category_path, remote: true do %>
      <%= button_tag "Create new Category", class: "btn btn-primary", style: "margin: 10px 0" %>
    <% end %>
    <table id="category-table" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Updated at</th>
          <th>Created at</th>
          <th style="text-align: center !important;">Edit</th>
          <th style="text-align: center !important;">Delete</th>
        </tr>
      </thead>
      <tbody id="category-item">
        <%= render "admin/category/item", categories: @categories %>
      </tbody>
      <tfoot>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Updated at</th>
          <th>Created at</th>
          <th style="text-align: center !important;">Edit</th>
          <th style="text-align: center !important;">Delete</th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>